### ISSUE TITLE
Move post option not working with Google SEO URLs enabled

### ISSUE THREAD

**Issue by MyBB-Andro** [frostschutz/MyBB-Google-SEO#56]
Hi,

Move post option (introduced with 1.8 upgrade) on moderator tools not working when forum uses Google SEO thread URLs. It only works with default MyBB URLs. Please fix this issue.

@frostschutz

**Comment by frostschutz** [comment]
It's a known issue. Move Posts was added in MyBB 1.8 but there is no plugin hook to go along with it, so supporting it the same way Merge Threads would require Google SEO to patch yet another file or convice MyBB team to add the hook. I never got around to it.

There is a simple workaround, however. When MyBB asks you to provide an URL you can give it the newreply link instead of thread link and it will work. A post link, printthread link, etc. may also work. All of these contain the TID or PID that MyBB needs.

**Comment by euantorano** [comment]
We would probably be willing to add a hook I think @frostschutz - where would you want one adding?

**Comment by frostschutz** [comment]
moderation.php, case "do_multimoveposts": somewhere near the top (see case "do_merge": moderation_do_merge hook for reference.)

**Comment by euantorano** [comment]
Thanks, I'll bring it up with the rest of the team and hopefully get that added for 1.8.11.

**Comment by frostschutz** [comment]
@euantorano Thanks!

**Comment by frostschutz** [comment]
@MyBB-Andro feel free to test, you need these two changes:

https://github.com/mybb/mybb/commit/6a891e187c645a8795af827e9587bfb7dbd720f8

https://github.com/frostschutz/MyBB-Google-SEO/commit/904a63c8635891d204e15882b3998e447e84dc2d

**Comment by MyBB-Andro** [comment]
It worked i have tested it over my forum, thank you very much @frostschutz @euantorano 😃
